# Generated by Django 5.0.7 on 2024-07-27 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='states',
        ),
        migrations.AddField(
            model_name='forms',
            name='states',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.states'),
        ),
    ]
